# Generated by Django 6.0.4 on 2026-04-30 04:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('NOMINAL', 'Nominal'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('usage_limit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PROMOTION',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderPromotion',
            fields=[
                ('order_promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_promotions', to='orders.order')),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_promotions', to='promotions.promotion')),
            ],
            options={
                'db_table': 'ORDER_PROMOTION',
                'unique_together': {('promotion', 'order')},
            },
        ),
    ]
