# Generated by Django 5.2.6 on 2026-04-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='has_reserved_seating',
            field=models.BooleanField(default=False),
        ),
    ]
