# Generated by Django 6.0.4 on 2026-04-26 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_venue', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('kota', models.CharField(max_length=100)),
                ('kapasitas', models.PositiveIntegerField()),
            ],
        ),
    ]
