# Generated by Django 6.0.4 on 2026-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='has_reserved_seating',
            field=models.BooleanField(default=False),
        ),
    ]
