# Generated by Django 6.0.4 on 2026-04-30 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Lunas'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
